import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "The terms that govern using Nashemann as a vendor, influencer, or customer of any store on the platform.",
};

const SECTIONS = [
  {
    title: "1. What Nashemann is",
    body: `Nashemann ("we", "us", "the platform") provides the infrastructure independent businesses in Pakistan use to run their own branded online store — a storefront, order management, inventory, and payments — without building any of it themselves. Nashemann is not the seller of record for products listed on any individual vendor's store; each vendor is solely responsible for the products, descriptions, pricing, and fulfillment of their own storefront.`,
  },
  {
    title: "2. Accounts",
    body: `You must provide accurate information when creating an account (as a vendor, an influencer, or a customer of a vendor's store) and keep it up to date. You're responsible for activity under your account. One account can hold more than one role (for example, both a vendor and an influencer role) using the same login — each role's data stays separated internally, but the login credentials are shared.`,
  },
  {
    title: "3. Vendors",
    body: `Approval to open a store on Nashemann is at our discretion and generally reviewed within 24 hours of applying. Vendors are responsible for the legality, accuracy, and quality of everything they list, for fulfilling orders they accept, and for their own customer service. Nashemann's fees (pay-per-order or a flat monthly rate, as chosen at signup) are disclosed before a vendor commits and may change with reasonable notice. We may suspend or remove a store that violates these terms, applicable law, or engages in fraudulent activity.`,
  },
  {
    title: "4. Influencers",
    body: `The Influencer Program pays a share of platform revenue generated by businesses you refer, for the period disclosed at signup. Referral codes are personal to your account and may not be resold, shared publicly in a way that misrepresents them as a discount code, or used in paid advertising without our consent. We may adjust program terms or a specific referral's payout period going forward, not retroactively for revenue already earned.`,
  },
  {
    title: "5. Customers",
    body: `When you order from a store on Nashemann, your contract for that purchase is with the vendor, not with Nashemann. Payment, delivery, and return/refund policies are set by the individual vendor unless stated otherwise at checkout. Nashemann provides the checkout, order tracking, and support infrastructure, and will help mediate a dispute with a vendor in good faith, but is not itself liable for a vendor's fulfillment failures.`,
  },
  {
    title: "6. Payments",
    body: `Payments are processed through the methods a given store makes available at checkout. Platform fees charged to vendors are separate from, and not visible as a line item to, the customer. We do not store full card numbers ourselves — payment processing is handled by our payment providers under their own security standards.`,
  },
  {
    title: "7. Prohibited use",
    body: `You may not use Nashemann to list illegal goods or services, infringe someone else's intellectual property, submit fraudulent orders or reviews, attempt to bypass platform fees, or interfere with the platform's security or normal operation. We may suspend any account engaged in prohibited use without prior notice.`,
  },
  {
    title: "8. Your data",
    body: `We collect the information needed to operate your account and, for vendors, your store (contact details, order and product data, and usage data to keep the platform reliable). We don't sell your personal data. You can request an export or deletion of your account data at any time from your account settings, subject to records we're required to retain for legal, tax, or fraud-prevention purposes.`,
  },
  {
    title: "9. Liability",
    body: `Nashemann is provided on an "as is" basis. We work to keep the platform reliable and secure but don't guarantee uninterrupted availability. To the extent permitted by law, our liability for any claim relating to your use of the platform is limited to the fees you paid us (if any) in the three months before the claim arose. This doesn't limit liability for something that can't legally be limited, such as fraud.`,
  },
  {
    title: "10. Changes to these terms",
    body: `We may update these terms as the platform evolves. Material changes will be communicated by email or an in-app notice before they take effect. Continuing to use Nashemann after a change takes effect means you accept the updated terms.`,
  },
  {
    title: "11. Governing law",
    body: `These terms are governed by the laws of Pakistan. Any dispute arising from your use of Nashemann will be subject to the exclusive jurisdiction of the courts of Pakistan.`,
  },
  {
    title: "12. Contact",
    body: `Questions about these terms can be sent to hello@nashemann.store.`,
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-16 lg:py-24">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent-violet)]">Legal</p>
      <h1 className="font-display mt-2 text-3xl font-semibold tracking-tight text-[var(--text)] sm:text-4xl">
        Terms &amp; Conditions
      </h1>
      <p className="mt-3 text-sm text-[var(--text-faint)]">Last updated: August 2026</p>
      <p className="mt-6 text-[var(--text-muted)]">
        These terms apply to everyone who uses Nashemann — whether you&apos;re running a store, part of the
        Influencer Program, or shopping at a store built on Nashemann. Please read them before creating an account.
      </p>

      <div className="mt-10 space-y-8">
        {SECTIONS.map((s) => (
          <section key={s.title}>
            <h2 className="font-display text-lg font-semibold text-[var(--text)]">{s.title}</h2>
            <p className="mt-2 leading-relaxed text-[var(--text-muted)]">{s.body}</p>
          </section>
        ))}
      </div>
    </div>
  );
}
